### ISSUE TITLE
What is the difference between this repo and sindresorhus/awesome?

### ISSUE THREAD

**Issue by ooker777** [imq/awesome-projects#1]
As this repo was just created recently, I suppose you already know about https://github.com/sindresorhus/awesome/. In that case, why do you decide to open a new project? What is the difference between the two?

**Comment by imq** [comment]
i don't, but there are hundreds of similar projects that are related. but what i can tell you that i use this as bookmark.

**Comment by ooker777** [comment]
so it's more about your preferences, and you will not accept PRs because they aren't your bookmarks. Am I correct?

**Comment by imq** [comment]
you can fork or clone and customize it for yourself.

**Comment by ooker777** [comment]
So I take that you want to keep the bookmarks yourself. May I ask why you feel the need to make a website just for it? Because I think that your repo, or any of the bookmark service is enough for that?
